export const data = [
    {
      id: 1,
      name: "Celestron C11 XLT OTA",
      img: "https://www.rothervalleyoptics.co.uk/user/products/large/91067xlt.jpg",
      price: 3200,
      cat: "Cats",
    },
    {
      id: 2,
      name: "Schmidt-Cassegrain telescope SC 203/2032 EdgeHD 800 AVX GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/33055_1/Celestron-Schmidt-Cassegrain-telescope-SC-203-2032-EdgeHD-800-AVX-GoTo.jpg",
      price: 3300,
      cat: "Cats",
    },
    {
      id: 3,
      name: "Apochromatic refractor Pro APO 94/517 Triplet ED CEM26 LiteRoc",
      img: "https://nimax-img.de/Produktbilder/zoom/71255_0/Omegon-Apochromatic-refractor-Pro-APO-94-517-Triplet-ED-CEM26-LiteRoc.jpg",
      price: 3350,
      cat: "Refractors",
    },
    {
      id: 4,
      name: "Telescope AC 50/600 AZ",
      img: "https://nimax-img.de/Produktbilder/zoom/33243_1/Omegon-Telescope-AC-50-600-AZ.jpg",
      price: 75,
      cat: "Refractors",
    },
    {
      id: 5,
      name: "Apochromatic refractor Pro APO 85/560 ED Triplet CEM26 LiteRoc",
      img: "https://nimax-img.de/Produktbilder/zoom/71258_0/Omegon-Apochromatic-refractor-Pro-APO-85-560-ED-Triplet-CEM26-LiteRoc.jpg",
      price: 3800,
      cat: "Refractors",
    },
    {
      id: 6,
      name: "Schmidt-Cassegrain telescope SC 356/3910 EdgeHD 1400 CGX-L GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/54048_1/Celestron-Schmidt-Cassegrain-telescope-SC-356-3910-EdgeHD-1400-CGX-L-GoTo.jpg",
      price: 15500,
      cat: "Cats",
    },
    {
      id: 7,
      name: "Schmidt-Cassegrain telescope SC 279/2800 EdgeHD 1100 CGX GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/52300_1/Celestron-Schmidt-Cassegrain-telescope-SC-279-2800-EdgeHD-1100-CGX-GoTo.jpg",
      price: 7500,
      cat: "Cats",
    },
    {
      id: 8,
      name: "Dobson telescope N 102/640 DOB",
      img: "https://nimax-img.de/Produktbilder/zoom/45172_1/nmxvers_1666783928-Omegon-Dobson-telescope-N-102-640-DOB.jpg",
      price: 220,
      cat: "Dobson",
    },
    {
      id: 9,
      name: "Dobson telescope N 254/1200 StarSense Explorer DOB",
      img: "https://nimax-img.de/Produktbilder/zoom/75391_1/Celestron-Dobson-telescope-N-254-1200-StarSense-Explorer-DOB.jpg",
      price: 1450,
      cat: "Dobson",
    },
    {
      id: 10,
      name: "Dobson telescope Advanced X N 304/1500",
      img: "https://nimax-img.de/Produktbilder/zoom/53804_1/Omegon-Dobson-telescope-Advanced-X-N-304-1500.jpg",
      price: 980,
      cat: "Dobson",
    },
    {
      id: 11,
      name: "Dobson telescope N 254/1200 Skyliner FlexTube BD DOB GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/21051_0/Skywatcher-Dobson-telescope-N-254-1200-Skyliner-FlexTube-BD-DOB-GoTo.jpg",
      price: 1600,
      cat: "Dobson",
    },
    {
      id: 12,
      name: "Dobson telescope N 406/1800 Skyliner FlexTube BD DOB",
      img: "https://nimax-img.de/Produktbilder/zoom/21288_0/Skywatcher-Dobson-telescope-N-406-1800-Skyliner-FlexTube-BD-DOB.jpg",
      price: 980,
      cat: "Dobson",
    },
    {
      id: 13,
      name: "Dobson telescope N 305/1500 Skyliner FlexTube BD DOB GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/21052_0/Skywatcher-Dobson-telescope-N-305-1500-Skyliner-FlexTube-BD-DOB-GoTo.jpg",
      price: 2300,
      cat: "Dobson",
    },
    {
      id: 14,
      name: "Dobson telescope N 355/1600 Skyliner FlexTube BD SynScan DOB GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/21287_0/Skywatcher-Dobson-telescope-N-355-1600-Skyliner-FlexTube-BD-SynScan-DOB-GoTo.jpg",
      price: 3150,
      cat: "Dobson",
    },
  ];