export const data = [
    {
      id: 1,
      name: "Celestron C11 XLT OTA",
      img: "https://www.rothervalleyoptics.co.uk/user/products/large/91067xlt.jpg",
      price: 3200,
      cat: "Cats",
    },
    {
      id: 2,
      name: "Schmidt-Cassegrain telescope SC 203/2032 EdgeHD 800 AVX GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/33055_1/Celestron-Schmidt-Cassegrain-telescope-SC-203-2032-EdgeHD-800-AVX-GoTo.jpg",
      price: 3300,
      cat: "Cats",
    },
    {
      id: 3,
      name: "Apochromatic refractor Pro APO 94/517 Triplet ED CEM26 LiteRoc",
      img: "https://nimax-img.de/Produktbilder/zoom/71255_0/Omegon-Apochromatic-refractor-Pro-APO-94-517-Triplet-ED-CEM26-LiteRoc.jpg",
      price: 3350,
      cat: "Refractors",
    },
    {
      id: 4,
      name: "Telescope AC 50/600 AZ",
      img: "https://nimax-img.de/Produktbilder/zoom/33243_1/Omegon-Telescope-AC-50-600-AZ.jpg",
      price: 75,
      cat: "Refractors",
    },
    {
      id: 5,
      name: "Apochromatic refractor Pro APO 85/560 ED Triplet CEM26 LiteRoc",
      img: "https://nimax-img.de/Produktbilder/zoom/71258_0/Omegon-Apochromatic-refractor-Pro-APO-85-560-ED-Triplet-CEM26-LiteRoc.jpg",
      price: 3800,
      cat: "Refractors",
    },
    {
      id: 6,
      name: "Schmidt-Cassegrain telescope SC 356/3910 EdgeHD 1400 CGX-L GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/54048_1/Celestron-Schmidt-Cassegrain-telescope-SC-356-3910-EdgeHD-1400-CGX-L-GoTo.jpg",
      price: 15500,
      cat: "Cats",
    },
    {
      id: 6,
      name: "Schmidt-Cassegrain telescope SC 279/2800 EdgeHD 1100 CGX GoTo",
      img: "https://nimax-img.de/Produktbilder/zoom/52300_1/Celestron-Schmidt-Cassegrain-telescope-SC-279-2800-EdgeHD-1100-CGX-GoTo.jpg",
      price: 7500,
      cat: "Cats",
    },
  ];